apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terre.fullname" . }}
  namespace: {{ include "terre.namespace" . }}
  labels:
    {{- include "terre.labels" . | nindent 4 }}
data:
  config.yaml: |
    proxy:
      name: {{ tpl .Values.proxy.name . }}
      host: 0.0.0.0
      port: 7777
      password: "{{ .Values.proxy.password }}"
      maxPlayers: {{ .Values.proxy.maxPlayers }}
      {{- if not .Values.servers.autoDiscovery.enabled }}
      disabledPlugins:
        - k8s-server-finder
      {{- end }}
      {{- if .Values.servers.fixed }}
      servers:
        {{- range .Values.servers.fixed }}
        - name: {{ tpl .name $ }}
          address: {{ tpl .host $ }}:{{ default "7777" .port }}
          password: {{ .password }}
          allowAutoJoin: {{ .allowAutoJoin }}
        {{- end }}
      {{- end }}
