{{- if .Values.servers.autoDiscovery.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terre.fullname" . }}-server-finder
  namespace: {{ include "terre.namespace" . }}
  labels:
    {{- include "terre.labels" . | nindent 4 }}
data:
  config.yaml: |
    serverFinder:
      namespace: "{{ tpl .Values.servers.autoDiscovery.namespace . }}"
      labelSelector: "{{ .Values.servers.autoDiscovery.labelSelector }}"
{{- end }}
