{{- if .Values.servers.autoDiscovery.createServiceReaderRole }}
apiVersion: rbac.authorization.k8s.io/v1
{{- $namespace := tpl .Values.servers.autoDiscovery.namespace . }}
{{- $roleKind := "ClusterRole" }}
{{- if $namespace }}
  {{- $roleKind = "Role" }}
{{- end }}
kind: {{ $roleKind }}
metadata:
  name: {{ include "terre.fullname" . }}-service-reader
  namespace: {{ $namespace | default (include "terre.namespace" .) }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ printf "%sBinding" $roleKind }}
metadata:
  name: {{ include "terre.fullname" . }}-read-services
  namespace: {{ $namespace | default (include "terre.namespace" .) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "terre.serviceAccountName" . }}
    namespace: {{ include "terre.namespace" . }}
roleRef:
  kind: {{ $roleKind }}
  name: {{ include "terre.fullname" . }}-service-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
