apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terraria.fullname" . }}
  {{- include "terraria.namespace" . | nindent 2 }}
  labels:
    {{- include "terraria.labels" . | nindent 4 }}
data:
  serverconfig.txt: |
    port=7777
    upnp=0
    priority=1
    world={{ tpl .Values.world.name . }}.wld
    worldname={{ tpl .Values.world.name . }}
    autocreate={{ include "terraria.worldsize" . }}
    difficulty={{ include "terraria.difficulty" . }}
    {{- if include "terraria.tshock" . }}
    {{- /* tshock docs suggest to set max players in the terraria config 2 higher than the tshock config */}}
    maxplayers={{ add .Values.server.maxPlayers.base 2 }}
    {{- else }}
    maxplayers={{ .Values.server.maxPlayers.base }}
    {{- end }}
    worldrollbackstokeep={{ .Values.world.rollbacksToKeep }}
    language={{ .Values.server.language }}
    {{- if .Values.password }}
    password={{ .Values.server.password }}
    {{- end }}
    {{- if .Values.world.seed }}
    seed={{ .Values.world.seed }}
    {{- end }}
    slowliquids={{ int .Values.world.slowLiquids }}
    secure={{ int .Values.antiCheatProtection.enabled }}
  config.json: |
    {
      "Settings": {
        "ServerPassword": "{{ .Values.password }}",
        "ServerPort": 7777,
        "MaxSlots": {{ .Values.server.maxPlayers.base }},
        "ReservedSlots": {{ .Values.server.maxPlayers.reserved }},
        "ServerName": "{{ tpl .Values.server.name . }}",
        "UseServerName": true,
        "DebugLogs": {{ .Values.server.debugLoggingEnabled }},
        "SpawnProtection": {{ .Values.spawnProtection.enabled }},
        "SpawnProtectionRadius": {{ .Values.spawnProtection.radius }},
        "RangeChecks": {{ and .Values.antiCheatProtection.enabled .Values.antiCheatProtection.rangeChecks }},
        "HardcoreOnly": {{ .Values.hardcoreOnly }},
        "MediumcoreOnly": {{ .Values.mediumcoreOnly }},
        "DisableHardmode": {{ not .Values.hardmode.triggerable }},
        "AllowCrimsonCreep": {{ .Values.hardmode.spreadCrimson }},
        "AllowCorruptionCreep": {{ .Values.hardmode.spreadCorruption }},
        "AllowHallowCreep": {{ .Values.hardmode.spreadHallow }},
        "RestApiEnabled": {{ .Values.rest.enabled }},
        "RestApiPort": 7878,
        "LogRest": {{ .Values.rest.loggingEnabled }},
        "EnableTokenEndpointAuthentication": false,
        "RESTMaximumRequestsPerInterval": {{ .Values.rest.maxRequestsPerInterval }},
        "RESTRequestBucketDecreaseIntervalMinutes": {{ .Values.rest.requestBucketDecreaseIntervalMinutes }},
        "ApplicationRestTokens": {}
      }
    }
