apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraria.fullname" . }}
  {{- include "terraria.namespace" . | nindent 2 }}
  labels:
    {{- include "terraria.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  {{- with .Values.server.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.server.service.externalName }}
  externalName: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: server
      name: server
      protocol: TCP
      {{- with .Values.server.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "terraria.selectorLabels" . | nindent 4 }}
