name: Build Tools Image

on:
  push:
    branches:
      - master
    paths:
      - images/tools/**
      - .github/workflows/tools-image.yaml
  workflow_dispatch:

env:
  platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le
  repo: ghcr.io/cybermaxke

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./images/tools
          platforms: ${{ env.platforms }}
          push: true
          tags: ${{ env.repo }}/tools:latest
