name: Build tShock Images

on:
  push:
    branches:
      - master
    paths:
      - images/tshock/**
      - .github/workflows/tshock-images.yaml
  workflow_dispatch:

env:
  platforms: linux/amd64,linux/arm64
  repo: ghcr.io/cybermaxke

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: 1.4.4.9
            tshock: 5.2.0
          - version: 1.4.3.6
            tshock: 4.5.16
          - version: 1.4.2.3
            tshock: 4.5.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./images/tshock-${{ startsWith(matrix.tshock, '5.') && '5' || '4' }}
          platforms: ${{ env.platforms }}
          push: true
          build-args: |
            TERRARIA_VERSION=${{ matrix.version }}
            TSHOCK_VERSION=${{ matrix.tshock }}
          tags: |
            ${{ env.repo }}/terraria:tshock-${{ matrix.version }}
            ${{ env.repo }}/terraria:tshock-${{ matrix.version }}-${{ matrix.tshock }}
