name: Build TShock Image

on:
  push:
    branches:
      - master
#    paths:
#      - images/tshock/**

jobs:
  build-tshock-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./images/tshock
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le
          push: true
          # TODO: Get the version values somewhere?
          tags: |
            cybermaxke/terraria:tshock-latest
            cybermaxke/terraria:tshock-1.4.2.3
            cybermaxke/terraria:tshock-1.4.2.3-4.5.5